### ISSUE TITLE
no make after git clone latest release on Ubuntu 16.04

### ISSUE THREAD

**Issue by dxs95** [zcoinofficial/cpuminer#11]
argon2ref/blake2ba.c:263:3: note: in expansion of macro ‘STOREU’
   STOREU(&S->h[0], _mm_xor_si128(LOADU(&S->h[0]), row1l));
   ^
./argon2ref/blake2b-round.h:24:48: error: expected expression before ‘)’ token
 #define STOREU(p,r) _mm_storeu_si128((__m128i *)(p), r)
                                                ^
argon2ref/blake2ba.c:263:3: note: in expansion of macro ‘STOREU’
   STOREU(&S->h[0], _mm_xor_si128(LOADU(&S->h[0]), row1l));
   ^
./argon2ref/blake2b-round.h:24:48: error: expected expression before ‘)’ token
 #define STOREU(p,r) _mm_storeu_si128((__m128i *)(p), r)
                                                ^
argon2ref/blake2ba.c:264:3: note: in expansion of macro ‘STOREU’
   STOREU(&S->h[2], _mm_xor_si128(LOADU(&S->h[2]), row1h));
   ^
./argon2ref/blake2b-round.h:24:48: error: expected expression before ‘)’ token
 #define STOREU(p,r) _mm_storeu_si128((__m128i *)(p), r)
                                                ^
argon2ref/blake2ba.c:267:3: note: in expansion of macro ‘STOREU’
   STOREU(&S->h[4], _mm_xor_si128(LOADU(&S->h[4]), row2l));
   ^
./argon2ref/blake2b-round.h:24:48: error: expected expression before ‘)’ token
 #define STOREU(p,r) _mm_storeu_si128((__m128i *)(p), r)
                                                ^
argon2ref/blake2ba.c:268:3: note: in expansion of macro ‘STOREU’
   STOREU(&S->h[6], _mm_xor_si128(LOADU(&S->h[6]), row2h));
   ^
argon2ref/blake2ba.c: In function ‘ablake2b4rounds_compress’:
argon2ref/blake2ba.c:276:3: error: unknown type name ‘__m128i’
   __m128i row1l, row1h;
   ^
argon2ref/blake2ba.c:277:3: error: unknown type name ‘__m128i’
   __m128i row2l, row2h;
   ^
argon2ref/blake2ba.c:278:3: error: unknown type name ‘__m128i’
   __m128i row3l, row3h;
   ^
argon2ref/blake2ba.c:279:3: error: unknown type name ‘__m128i’
   __m128i row4l, row4h;
   ^
argon2ref/blake2ba.c:280:3: error: unknown type name ‘__m128i’
   __m128i b0, b1;
   ^
argon2ref/blake2ba.c:281:3: error: unknown type name ‘__m128i’
   __m128i t0, t1;
   ^
In file included from argon2ref/blake2ba.c:25:0:
./argon2ref/blake2b-round.h:23:37: error: ‘__m128i’ undeclared (first use in this function)
 #define LOADU(p)  _mm_loadu_si128( (__m128i *)(p) )
                                     ^
argon2ref/blake2ba.c:313:11: note: in expansion of macro ‘LOADU’
   row1l = LOADU(&S->h[0]);
           ^
./argon2ref/blake2b-round.h:23:46: error: expected expression before ‘)’ token
 #define LOADU(p)  _mm_loadu_si128( (__m128i *)(p) )
                                              ^
argon2ref/blake2ba.c:313:11: note: in expansion of macro ‘LOADU’
   row1l = LOADU(&S->h[0]);
           ^
./argon2ref/blake2b-round.h:23:46: error: expected expression before ‘)’ token
 #define LOADU(p)  _mm_loadu_si128( (__m128i *)(p) )
                                              ^
argon2ref/blake2ba.c:314:11: note: in expansion of macro ‘LOADU’
   row1h = LOADU(&S->h[2]);
           ^
./argon2ref/blake2b-round.h:23:46: error: expected expression before ‘)’ token
 #define LOADU(p)  _mm_loadu_si128( (__m128i *)(p) )
                                              ^
argon2ref/blake2ba.c:315:11: note: in expansion of macro ‘LOADU’
   row2l = LOADU(&S->h[4]);
           ^
./argon2ref/blake2b-round.h:23:46: error: expected expression before ‘)’ token
 #define LOADU(p)  _mm_loadu_si128( (__m128i *)(p) )
                                              ^
argon2ref/blake2ba.c:316:11: note: in expansion of macro ‘LOADU’
   row2h = LOADU(&S->h[6]);
           ^
./argon2ref/blake2b-round.h:23:46: error: expected expression before ‘)’ token
 #define LOADU(p)  _mm_loadu_si128( (__m128i *)(p) )
                                              ^
argon2ref/blake2ba.c:317:11: note: in expansion of macro ‘LOADU’
   row3l = LOADU(&ablake2b_IV[0]);
           ^
./argon2ref/blake2b-round.h:23:46: error: expected expression before ‘)’ token
 #define LOADU(p)  _mm_loadu_si128( (__m128i *)(p) )
                                              ^
argon2ref/blake2ba.c:318:11: note: in expansion of macro ‘LOADU’
   row3h = LOADU(&ablake2b_IV[2]);
           ^
./argon2ref/blake2b-round.h:23:46: error: expected expression before ‘)’ token
 #define LOADU(p)  _mm_loadu_si128( (__m128i *)(p) )
                                              ^
argon2ref/blake2ba.c:319:25: note: in expansion of macro ‘LOADU’
   row4l = _mm_xor_si128(LOADU(&ablake2b_IV[4]), LOADU(&S->t[0]));
                         ^
./argon2ref/blake2b-round.h:23:46: error: expected expression before ‘)’ token
 #define LOADU(p)  _mm_loadu_si128( (__m128i *)(p) )
                                              ^
argon2ref/blake2ba.c:320:25: note: in expansion of macro ‘LOADU’
   row4h = _mm_xor_si128(LOADU(&ablake2b_IV[6]), LOADU(&S->f[0]));
                         ^
./argon2ref/blake2b-round.h:24:48: error: expected expression before ‘)’ token
 #define STOREU(p,r) _mm_storeu_si128((__m128i *)(p), r)
                                                ^
argon2ref/blake2ba.c:327:3: note: in expansion of macro ‘STOREU’
   STOREU(&S->h[0], _mm_xor_si128(LOADU(&S->h[0]), row1l));
   ^
./argon2ref/blake2b-round.h:24:48: error: expected expression before ‘)’ token
 #define STOREU(p,r) _mm_storeu_si128((__m128i *)(p), r)
                                                ^
argon2ref/blake2ba.c:328:3: note: in expansion of macro ‘STOREU’
   STOREU(&S->h[2], _mm_xor_si128(LOADU(&S->h[2]), row1h));
   ^
./argon2ref/blake2b-round.h:24:48: error: expected expression before ‘)’ token
 #define STOREU(p,r) _mm_storeu_si128((__m128i *)(p), r)
                                                ^
argon2ref/blake2ba.c:331:3: note: in expansion of macro ‘STOREU’
   STOREU(&S->h[4], _mm_xor_si128(LOADU(&S->h[4]), row2l));
   ^
./argon2ref/blake2b-round.h:24:48: error: expected expression before ‘)’ token
 #define STOREU(p,r) _mm_storeu_si128((__m128i *)(p), r)
                                                ^
argon2ref/blake2ba.c:332:3: note: in expansion of macro ‘STOREU’
   STOREU(&S->h[6], _mm_xor_si128(LOADU(&S->h[6]), row2h));
   ^
argon2ref/blake2ba.c: In function ‘ablake2b_compress_old’:
argon2ref/blake2ba.c:373:0: warning: "ROUND" redefined
 #define ROUND(r)                                                               
 ^
In file included from argon2ref/blake2ba.c:25:0:
./argon2ref/blake2b-round.h:150:0: note: this is the location of the previous definition
 #define ROUND(r) \
 ^
argon2ref/blake2ba.c: In function ‘ablake2b_compress_test’:
argon2ref/blake2ba.c:402:8: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
 printf("coming here S %08x %08x %08x %08x\n", S->t[0], S->t[1], S->f[0], S->f[1
        ^
argon2ref/blake2ba.c:402:8: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
argon2ref/blake2ba.c:402:8: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 4 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
argon2ref/blake2ba.c:402:8: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 5 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
Makefile:2644: «argon2ref/cpuminer-blake2ba.o»

**Comment by dxs95** [comment]
and please add #include <stdint.h> in file -> bosjansson.h  .
Project from sourse.zip for win build with replase in all files:
bosjansson.h -> bos-jansson/bosjansson.h
jansson_config.h -> bos-jansson/jansson_config.h
jansson_private_config.h -> bos-jansson/jansson_private_config.h

Best regards.

**Comment by dxs95** [comment]
Thanks for all  !!!
Build cpuminer in Ubuntu 16.04 completed successfully !!!!

**Comment by djm34** [comment]
? (regarding your first message, there was a bug in linux compilation and it was fixed)
the linux build shouldn't be made from the zip file included in the release. 
here the procedure, which does requires any modification of any kind (especially not in bos-janson)
./autogen.sh
./configure  --with-crypto --with-curl
make
