### ISSUE TITLE
is cpuminer by djm and cpuminer-multi the same ?

### ISSUE THREAD

**Issue by agentpatience** [zcoinofficial/cpuminer#12]
CPUMiner-Multi the same as cpuminer djm?

I am looking to find a stable MTP miner for ubuntu. Can you direct me to my options?

**Comment by agentpatience** [comment]
sorry, I think I found out the answer ion my own, it seems that I should use the cpuminer-multi project updated 2 days ago.

**Comment by djm34** [comment]
where ? 
I develop only one project which is where you post this issue
This project is based on cpuminer-multi from tpruvot. But the official one is this one here:

https://github.com/zcoinofficial/cpuminer

**Comment by agentpatience** [comment]
Sorry I found an older project that confused me. I was able to compile your latest code on Dual Xeon 2980.

**Comment by agentpatience** [comment]
when I try to follow build directions and command line instructions for mtp I get:

jeff@tester9:~/cpuminer-multi$ ./cpuminer -a mtp -o stratum+tcp://xzc.2miners.com:8080 -u a1jdNZbAdNKCh33VdJtCvdjnXc4VbSXmfC.2980 -p x
** cpuminer-multi 1.3.6 by tpruvot@github **
BTC donation address: 1FhDPLPpw18X4srecguG3MxJYe4a1JsZnd (tpruvot)

[2019-03-12 16:36:07] Unknown algo parameter 'mtp'
Try `cpuminer-multi --help' for more information.

**Comment by agentpatience** [comment]
oh, i must use this git:
https://github.com/zcoinofficial/cpuminer.git ?

**Comment by djm34** [comment]
well, I think it makes sense to pick up the software where you open the issue and not in some other place...

**Comment by agentpatience** [comment]
Ok, we can close this ticket.
