### ISSUE TITLE
build issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by kachind** [zcoinofficial/cpuminer#2]
I encountered a bunch of issues while trying to build the new commit... here is how I tried to resolve

autogen error
---
Invoking ./autogen.sh produces an error, since the compat/jansson directory is now missing, but compat/makefile.am references "compat/jansson/Makefile.in".

fixed this:

cd compat
mkdir jansson
mv bos-jansson/src/* jansson

---

another autogen error
---

"libtool library used but LIBTOOL undefined"

to resolve this error, I added an LT_INIT line to beginning of configure.ac, then
libtoolize
aclocal
autoconf

and then autogen works as expected

---
missing header error
---

./configure CFLAGS='-march=native' --with-crypto--with-curl
make

output:
fatal error: bosjansson.h: No such file or directory

solution:
cp  compat/jansson/bosjansson.h .

---
make error
---

after resolving the above, make will compile for a while, then encounters the following error:

./libtool: line 7486: cd: yes/lib: No such file or directory
libtool:    error: cannot determine absolute directory name of 'yes/lib'

This is probably related to the libtoolize command I used to resolve the earlier issue with the missing LIBTOOL library. I haven't been able to resolve it and at this point I'm not sure what I'm doing.

It seems to be issue with broken linking / dependencies, particularly with jansson.

Would appreciate any help

**Comment by djm34** [comment]
please check out the master which were committed last night

**Comment by kachind** [comment]
New commit resolved issue. Closing, thanks.
