### ISSUE TITLE
On windows MTP stops after some times

### ISSUE THREAD

**Issue by ghost** [zcoinofficial/cpuminer#23]
Any idea about that bug? I simply run my command and after a bit it simply stops without any error

**Comment by djm34** [comment]
like this difficult to say, I would need a log file, debug info...

if you can run ccminer with --protocol-dump --debug and send me the part of log when it crashes may-be I could find out something

**Comment by ghost** [comment]
> like this difficult to say, I would need a log file, debug info...
> 
> if you can run ccminer with --protocol-dump --debug and send me the part of log when it crashes may-be I could find out something

I have tried but nothing, no error or something else. It just stops

**Comment by bmagnien** [comment]
having the same issue - don't see any log/crash file generated. cmd prompt just exits out.

**Comment by djm34** [comment]
immediately or after some times ?

**Comment by ghost** [comment]
> immediately or after some times ?

I have moved to gentoo, anyway IIRC it was after some time (sometimes 30 secs, sometimes 10 mins)

**Comment by bmagnien** [comment]
It runs at upwards of 300+ khs on my 5950x for about 10 mins alongside the
gpu miner (trex). Both report as separate workers to my pool. Then I come
back to my computer and the cpu prompt is just gone and the worker has
fallen off my pool reporting. I’ve tried to download an older version to
see if it helps. Cpu temps below 80c on a custom loop

**Comment by djm34** [comment]
can you check mem usage before it crashes

**Comment by bmagnien** [comment]
4.386 gb on the cpuminer cmd process, out of 32 gb total. Total system mem
in use is at 28% of 32gb. so far the .exe from before the thread. so far
the .exe from 0.1.1 - before the thread affinity addition - seems to be
running longer for me, and at about 20khs higher.

**Comment by bmagnien** [comment]
0.1.1 going strong for close to an hour now alongside trex, and at ~40khs higher than 0.1.2. will report back if i get more crashes
